/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { route$_T } from './route$_b.js'
import type { route_query$_T } from './route_query$_b.js'
export interface route_ctx_I {
	route$?:route$_T
	route_query$?:route_query$_T
}
